name: Get Github Deployment Environments

on:
  push:
    branches:
      - feature/get_deployment_envs

env:
  BASE_URI: 'https://api.github.com/repos/'
  HEADER: '{"Content-Type": "application/vnd.github+json"}'
jobs:
  list_envs:
    name: List Deployment Environments
    runs-on: ubuntu-latest
    steps:
      - id: request
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ env.BASE_URI }}${{ github.repository }}/environments"
          method: GET
          customHeaders: '${{ env.HEADER }}'
          bearerToken: ${{ secrets.OAUTH_TOKEN }}
      - id: response
        run: |
          echo "${{ fromJson(steps.request.outputs.response).environments['0'].name{} }}"
