name: Get Github Deployment Environments

on:
  push:
    branches:
      - feature/get_deployment_envs

env:
  BASE_URI: 'https://api.github.com/repos/'
  HEADER: '"Content-Type": "application/vnd.github+json"'
jobs:
  matrix:
    name: List Deployment Environments
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          $global:base_uri="${{ env.BASE_URI }}"
          $global:token="${{ github.token }}"
          $global:header=@{
            content_type = 'application/vnd.github+json'
          }

          function get_deployments(){
            $uri="$global:base_uri${{ github.repository }}/environments"
            $header=$global:header
            $response = Invoke-RestMethod -Uri $uri -Headers $header -Method GET

            return $uri
          }

          $matrix=get_deployments
          Write-Host $matrix
        shell: pwsh
