name: Get Github Deployment Environments

on:
  push:
    branches:
      - feature/get_deployment_envs

env:
  BASE_URI: 'https://api.github.com/repos/'
  HEADER: '{"Content-Type": "application/vnd.github+json"}'
jobs:
  list_envs:
    name: List Deployment Environments
    runs-on: ubuntu-latest
    steps:
      - id: request
        run: |
          curl \
            -H "${{ env.HEADER }}" \
            -H "Authorization: Bearer ${{ github.token }}" \
            ${{ env.BASE_URI }}${{ github.repository }}/environments
