name: Get Github Deployment Environments

on:
  push:
    branches:
      - feature/get_deployment_envs

env:
  BASE_URI: 'https://api.github.com/repos/'
  HEADER: '"Content-Type": "application/vnd.github+json"'
jobs:
  matrix:
    name: List Deployment Environments
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          function get_environments(){
            $token="${{ github.token }}"
            $header=@{
              content_type = 'application/vnd.github+json'
              Authorization = "Bearer $token"
            }
            $base_uri="${{ env.BASE_URI }}"
            $uri="$base_uri"+"${{ github.repository }}/environments"

            $response = Invoke-RestMethod -Uri $uri -Headers $header -Method GET
            $data = @{
              environment = $response.environments.name
            }

            return $data
          }

          $environments=get_environments
          $matrix=$environments | ConvertTo-JSON
          echo "::set-output name=matrix::$matrix"
        shell: pwsh
  check_matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix


