name: Get Github Deployment Environments

on:
  push:
    branches:
      - feature/get_deployment_envs

env:
  BASE_URI: 'https://api.github.com/repos/'
  HEADER: '"Content-Type": "application/vnd.github+json"'
jobs:
  matrix:
    name: List Deployment Environments
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          response=$(curl \
            -H "${{ env.HEADER }}" \
            -H "Authorization: Bearer ${{ github.token }}" \
            ${{ env.BASE_URI }}${{ github.repository }}/environments | jq -c '.environments[] | .name' )

          echo $response
          
          environments=$(echo $matrix | jq -c '.environments[] | .name')
          echo "::set-output name=matrix::$environments"
  check-matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
