name: Create Terraform Cloud Organization

on:
  push:
    branches:
      - main
      - dev
      - feature/**
jobs:
  checks:
    name: Check if Terraform Cloud Organization Already exists
    runs-on: ubuntu-latest
    outputs:
      response: ${{ steps.request.outputs.stdout }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: 'vmware'
    steps:
      - id: request
        run: |
          $header=@{
            Authorization = "Bearer ${{ secrets.TF_API_TOKEN }}"
            content_type = 'application/vnd.api+json'
          }
          $uri = "${{ env.BASE_URI }}organizations"
          $new = "${{ matrix.environment }}"
          $response = Invoke-RestMethod -Uri "$uri" -Method Get -Headers $header
          $array = @()
          foreach ($id in $response.data.id){
            $array += $id
          }

          if (-Not ($array -contains $new)){
            echo "create_org=true" >> $env:GITHUB_ENV
            return $false
          } else {
            echo "create_org=false" >> $env:GITHUB_ENV
            return $true
          }
        shell: pwsh
      - id: output
        run: |
          echo '${{ env.create_org }}'



