name: Create Terraform Cloud Organization

on:
  push:
    branches:
      - main
      - dev
      - feature/**
env:
  BASE_URI: 'https://app.terraform.io/api/v2/'
  HEADER: '{"Content-Type": "application/vnd.api+json"}'
jobs:
  check:
    name: Check if Terraform Cloud Organization Already exists
    runs-on: ubuntu-latest
    outputs:
      create: ${{ fromJson(steps.myRequest.outputs.response).data['0'].id }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: 'vmware'
          - environment: 'TheBrynards'
    steps:
      - id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ env.BASE_URI }}/organizations?q[name]=${{ matrix.environment }}"
          method: GET
          customHeaders: '${{ env.HEADER }}'
          bearerToken: ${{ secrets.TF_API_TOKEN }}
      - name: Show Response
        run: |
          echo "${{ fromJson(steps.myRequest.outputs.response).data['0'].id }}"
          echo '::set-output create=${{ fromJson(steps.myRequest.outputs.response).data['0'].id }}'
      - name: Create Org if it doesn't exist
        id: tfCreate
        if: fromJson(steps.myRequest.outputs.response).data['0'].id  == null
        run: echo "Creating Org"


