name: Create Terraform Cloud Organization

on:
  push:
    branches:
      - main
      - dev
      - feature/**

env:
  BASE_URI: 'https://app.terraform.io/api/v2/'
  HEADER: '{"Content-Type": "application/vnd.api+json"}'


jobs:
  checks:
    name: Check if Terraform Cloud Organization Already exists
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: 'vsphere'
    steps:
      - id: check_org
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ env.BASE_URI }}/organizations"
          method: GET
          customHeaders: '${{ env.HEADER }}'
          bearerToken: ${{ secrets.TF_API_TOKEN }}



