name: Create Terraform Cloud Organization

on:
  push:
    branches:
      - main
      - dev
      - feature/**

env:
  BASE_URI: 'https://app.terraform.io/api/v2/'
  HEADER: '{"Content-Type": "application/vnd.api+json"}'


jobs:
  checks:
    name: Check if Terraform Cloud Organization Already exists
    runs-on: ubuntu-latest
    outputs:
      response: ${{ steps.request.outputs.stdout }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: 'vmware'
    steps:
      - id: request
        run: |
          $header=@{
            Authorization = "Bearer ${{ secrets.TF_API_TOKEN }}"
            content_type = 'application/vnd.api+json'
          }
          $uri = "${{ env.BASE_URI }}organizations"
          $new = "${{ matrix.environment }}"
          $response = Invoke-RestMethod -Uri "$uri" -Method Get -Headers $header
          $array = @()
          foreach ($id in $response.data.id){
            $array += $id
          }

          if (-Not ($array -contains $new)){
            Write-Host -ForegroundColor Yellow "Organization does not exist!"
            return $false
          } else {
            Write-Host -ForegroundColor Green "Organization already exists!"
            return $true
          }
        shell: pwsh
      - name: Check outputs
        run: |
          echo '${{ steps.request.stdout }}'



